swagger: "2.0"
info:
  title: "Pet API"
  version: "1.0.0"
  description: "Apis for managin the pet sore"
  license:
    name: "Apache 2.0"
    url: "https://bing.com"
  contact:
    email: "oscargl2017@hotmail.com"
    name: "El oga"
    url: "https://bing.com"
  termsOfService: "https://bing.com"
basePath: '/api'
paths:
  /pets:
    get:
      description: "Gets all pets on the pet store"
      operationId: "GetAllPets"
      produces:
        - application/json
        - application/xml
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items: 
              $ref: "#/definitions/Pet"
        404:
          description: "No pets found"
      deprecated: false
    post:
      description: "Adds a new pet to the store"
      operationId: "AddPet"
      produces:
        - application/json
        - application/xml
      parameters:
        - name: "body"
          in: body
          description: "Pet data"
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Pet"
        400:
          description: "Wrong pet info"
      deprecated: false
  /pets/{id}:
    get:
      description: "Get a pet by id"
      operationId: "GetPet"
      produces: 
        - application/json
        - application/xml
      parameters:
        - name: id
          in: path
          type: integer
          description: "Pet internal identifier"
          required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Pet"
        404:
          description: "Pet not found"
      deprecated: false
    put:
      description: "Updates a Pet"
      operationId: "UpdatePet"
      produces:
        - application/json
        - application/xml
      parameters:
        - name: "id"
          in: path
          type: integer
          description: "Pet internal identifier"
          required: true
        - name: body
          in: body
          description: "Pet data"
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Pet"
        404:
          description: "Not foud"
      deprecated: false
definitions:
  Pet:
    required:
      - "id"
      - "tag"
    properties: 
      id:
        type: integer
        format: "int32"
        example: "1234"
        description: "Pet internal identifier"
      tag:
        type: string
        example: "ABC-123"
        description: "Pet's international tag"
      name:
        type: string
        example: "Doggy"
        description: "Name of the pet"
         