apiVersion: v1
kind: PersistentVolume
metadata:
  name: cronjob-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-pvc
spec:
  storageClassName: local-storage
  volumeName: cronjob-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  