apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization
spec:
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
      - name: organization
        image: containersoga/hrorganization
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: HR_BD_CON
            valueFrom:
              secretKeyRef:
                name: hrsecrets
                key: databaseUrl
          - name: HR_OKTA_AUTHORITY
            valueFrom:
              configMapKeyRef:
                name: hrconfigs
                key: oktaIssuer
          - name: HR_OKTA_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: hrconfigs
                key: oktaAudience
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 100
          timeoutSeconds: 200
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 100
          timeoutSeconds: 200
---
apiVersion: v1
kind: Service
metadata:
  name: organization
  labels:
    app: organization
spec:
  selector:
    app: organization
  ports:
  - port: 5010
    targetPort: 80
    protocol: TCP
    name: http