apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: organization-autoscaler
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20 
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  scaleTargetRef:
    kind: Deployment
    name: organization
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi

